services:
  check:
    image: ghcr.io/jonapoul/atlas:latest
    volumes:
      - $HOME/.gradle:/home/gradle/.gradle
      - ..:/atlas
    working_dir: /atlas
    command: >
      /bin/bash -c "
      gradle -Dorg.gradle.java.home=/opt/java/openjdk/ check &&
      gradle -Dorg.gradle.java.home=/opt/java/openjdk/ atlasGenerate -p samples/sample-d2 &&
      gradle -Dorg.gradle.java.home=/opt/java/openjdk/ atlasGenerate -p samples/sample-graphviz &&
      gradle -Dorg.gradle.java.home=/opt/java/openjdk/ atlasGenerate -p samples/sample-mermaid
      "
