services:
  base:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
    image: ghcr.io/jonapoul/modular:latest
    volumes:
      - $HOME/.gradle:/home/gradle/.gradle
      - ..:/modular
    working_dir: /modular

  check:
    extends: base
    command: gradle -Dorg.gradle.java.home=/opt/java/openjdk/ check

  build:
    extends: base
    command: gradle -Dorg.gradle.java.home=/opt/java/openjdk/ build

  generate-samples:
    extends: base
    command: >
      /bin/bash -c "
      gradle -Dorg.gradle.java.home=/opt/java/openjdk/ modularGenerate -p samples/sample-graphviz &&
      gradle -Dorg.gradle.java.home=/opt/java/openjdk/ modularGenerate -p samples/sample-mermaid
      "
