---
complexity:
  LongParameterList:
    functionThreshold: 8
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInFiles: 20
    thresholdInInterfaces: 20

style:
  MaxLineLength:
    maxLineLength: 120
