---
complexity:
  LongParameterList:
    allowedConstructorParameters: 8
    allowedFunctionParameters: 8
    ignoreDefaultParameters: true
  TooManyFunctions:
    allowedFunctionsPerClass: 20
    allowedFunctionsPerFile: 20
    allowedFunctionsPerInterface: 20

style:
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5
  ForbiddenComment:
    allowedPatterns: 'TODO.? https://github\.com/jonapoul/modular/issues/\d+'
  MaxLineLength:
    maxLineLength: 120
  ReturnCount:
    max: 4
    excludeGuardClauses: true
