---
complexity:
  LongParameterList:
    constructorThreshold: 8
    functionThreshold: 8
    ignoreDefaultParameters: true
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInFiles: 20
    thresholdInInterfaces: 20

style:
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 5
  MaxLineLength:
    maxLineLength: 120
