name: Docker Login
description: Log in to the GitHub container registry

runs:
  using: composite
  steps:
    - name: Login to registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
