name: Docker Login
description: Log in to the GitHub container registry

runs:
  using: composite
  steps:
    - name: Login to registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
