name: Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  checks: write

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  main-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: ./config/gitleaks.toml

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          add-job-summary: on-failure

      - name: Build
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: docker/docker-compose.yml
          services: modular
          run: ./gradlew build
