name: Publish Snapshot

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  checks: write

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get version
        id: version
        run: |
          GRADLE_VERSION=$(grep VERSION_NAME gradle.properties | cut -d "=" -f 2)
          echo "GRADLE_VERSION=$GRADLE_VERSION"
          echo "value=$GRADLE_VERSION" >> $GITHUB_OUTPUT

      - name: Exit if version isn't a snapshot
        if: "!contains(steps.version.outputs.value, '-SNAPSHOT')"
        run: |
          echo "Not a snapshot version, backing out"
          exit 1

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish snapshot
#        if: github.repository == 'jonapoul/atlas' && github.ref == 'refs/heads/main'
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
        run: docker compose -f docker/docker-compose.yml run --rm publish
