name: Publish Snapshot

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  checks: write

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    container:
      image: gradle:9.1.0-jdk21
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get version
        id: version
        run: |
          GRADLE_VERSION="$(grep VERSION_NAME gradle.properties | cut -d "=" -f 2)"
          echo "GRADLE_VERSION=$GRADLE_VERSION"
          echo "value=$GRADLE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Publish snapshot
        if: |
          github.repository == 'jonapoul/atlas' &&
          github.ref == 'refs/heads/main' &&
          contains(steps.version.outputs.value, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
        run: ./gradlew publishToMavenCentral -x dokkaGeneratePublicationHtml
